In [87]:
import pandas as pd

import numpy as np

import pyfpgrowth

In [88]:
df = pd.read_csv('www.csv', sep='\t')

In [89]:
print ( df.shape )
print ( df. head () )

(9999, 502)
    UserId                       Query horse http photos in  a up the company  \
0  2304236    washington state lottery     f    f      f  f  f  f   f       f
1  7832793  jc justin been throwing up     f    f      f  f  f  t   f       f
2  9167300        terrace at greenhill     f    f      f  f  f  f   f       f
3    55733           vegas sports line     f    f      f  f  f  f   f       f
4  2686572           the disabled list     f    f      f  f  f  f   t       f

   ... houston why yahoo louis tn maine test local tennessee santa
0  ...       f   f     f     f  f     f    f     f         f     f
1  ...       f   f     f     f  f     f    f     f         f     f
2  ...       f   f     f     f  f     f    f     f         f     f
3  ...       f   f     f     f  f     f    f     f         f     f
4  ...       f   f     f     f  f     f    f     f         f     f

[5 rows x 502 columns]

In [90]:
df.dropna()

,UserId,Query,horse,http,photos,in,a,up,the,company,...,houston,why,yahoo,louis,tn,maine,test,local,tennessee,santa
0,2304236,washington state lottery,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
1,7832793,jc justin been throwing up,f,f,f,f,f,t,f,f,...,f,f,f,f,f,f,f,f,f,f
2,9167300,terrace at greenhill,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
3,55733,vegas sports line,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
4,2686572,the disabled list,f,f,f,f,f,f,t,f,...,f,f,f,f,f,f,f,f,f,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,2784836,421-b tax abatement for staten island,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9995,8920677,appollo theatre chicago,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9996,4139696,ford box trucks,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9997,728654,apartments for rent,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f
9998,412723,prism online casino,f,f,f,f,f,f,f,f,...,f,f,f,f,f,f,f,f,f,f

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 502 entries, UserId to santa
dtypes: int64(1), object(501)
memory usage: 38.3+ MB

In [92]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9994    False
9995    False
9996    False
9997    False
9998    False
Length: 9999, dtype: bool

In [93]:
df.loc[:, df.isnull().any()]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[9999 rows x 0 columns]

In [94]:
print('Number of rows before removing duplicates:', len(df))
df = df.drop_duplicates('Query', keep='first')
df.reset_index(drop=True, inplace=True)
print('Number of rows after removing duplicates:', len(df))

Number of rows before removing duplicates: 9999
Number of rows after removing duplicates: 9816

In [95]:
df.count()

UserId       9816
Query        9816
horse        9816
http         9816
photos       9816
             ...
maine        9816
test         9816
local        9816
tennessee    9816
santa        9816
Length: 502, dtype: int64

In [ ]:
associations = df['Query'].apply(lambda x: x.split()).tolist()
num_records = len(associations)

[['washington', 'state', 'lottery'],
 ['jc', 'justin', 'been', 'throwing', 'up'],
 ['terrace', 'at', 'greenhill'],
 ['vegas', 'sports', 'line'],
 ['the', 'disabled', 'list'],
 ['coffee', 'shop', 'franchise'],
 ['the', 'home', 'depot'],
 ['chapter', '10', 'summary', 'la', 'catrina'],
 ['free', 'hot', 'and', 'wild', 'videos'],
 ['naked', 'male', 'athletes'],
 ['venetian', 'hotel', 'value', 'days'],
 ['blank', 'business', 'recomendation', 'forms'],
 ['line', 'of', 'credit'],
 ['n', 'y', 's', 'e', 'evergreen', 'solar'],
 ["hawaii's", 'state', 'bird'],
 ['ohio', 'fair', 'plan'],
 ['butterfly', 'life', 'in', 'foster', 'city'],
 ['busted', 'stuff', 'group'],
 ['new', 'york', 'state', 'penal', 'laws'],
 ['kentucky', 'blue', 'grass'],
 ["earl's", 'in', 'abbeville'],
 ['mon', 'cheri', 'dresses'],
 ['absolute', 'poker', '.com'],
 ['broward', 'county', 'sheriffs', 'office'],
 ['nattokinase', 'and', 'ligament', 'healing'],
 ['boston', 'university', 'graduates1970'],
 ['cell', 'phone', 'secrets'],
 ['average',
  'time',
  'spent',
  'doing',
  'homework',
  'for',
  'a',
  '9',
  'year',
  'old'],
 ['homes', 'for', 'sale', 'by', 'owner'],
 ['make', 'a', 'word', 'search'],
 ['best', 'westen', 'hotels'],
 ['john', 'sterling', 'hancock'],
 ['fidelity', 'high', 'yield'],
 ['futures', 'and', 'options', 'brokers'],
 ['http', 'yahoo', '.com'],
 ['orange.cats', 'for', 'free'],
 ['lonely', 'day', 'music', 'video'],
 ['deathtrap', 'by', 'ira', 'levin', 'overview'],
 ['gregory', 'diehl', 'md'],
 ['ebay', 'medical', 'roll', 'walkers'],
 ['suprior', 'court', 'caden', 'county'],
 ['seabrook', 'flower', 'shop'],
 ['flaming', 'river', 'custom', 'steering'],
 ['flag', 'of', 'china'],
 ['citing', 'websites', 'in', 'your', 'work'],
 ['paterson', 'public', 'housing', 'authority', 'senior', 'citizens'],
 ['free', 'yellow', 'pages'],
 ['dmv', 'in', 'ventura'],
 ['more', 'german', 'chocolate', 'cakes', 'recipes'],
 ['typical', 'adult', 'problems', 'of', 'childhood', 'clergy', 'abuse'],
 ['heavely', 'ham', 'roanoke', 'va'],
 ['girl', 'had', 'sex'],
 ['excerpt', 'from', 'we', 'speak', 'your', 'names'],
 ['new', 'jersey', 'home', 'care'],
 ['why', 'do', 'we', 'say', 'the', 'pledge', 'of', 'allegiance'],
 ['dogs', 'and', 'anxiety'],
 ['keystone', 'realty', 'louisiana'],
 ['marriott', 'marco', 'island', 'resort', 'golf', 'club', 'and', 'spa'],
 ['black', 'silicone', 'case', 'for', 'mp4'],
 ['t', '-', 'rockaxle'],
 ['hedgerow', 'theater', 'pa'],
 ['wayne', 'country', 'tax', 'information'],
 ['weight', 'watchers', 'and', 'omaha', 'locations'],
 ['novena', 'to', 'the', 'holy', 'spirit'],
 ['capital', 'city', 'bank', 'online'],
 ['arizona', 'republic', 'classified'],
 ['food', 'service', 'counters'],
 ['www.copiah', 'lincolon', 'comm', 'college'],
 ['wedding', 'portrates', 'of', 'black', 'couples'],
 ['greenbelt', 'parties', 'the', 'lion', 'club'],
 ['black', 'america', 'web'],
 ['monopoly', 'tycoon', 'activation', 'code'],
 ['kennedy', 'space', 'center'],
 ['myspace', 'links', 'hide', 'comments'],
 ['curtis', 'john', 'cregan'],
 ['nasty', 'phone', 'talk'],
 ['cable', 'management', 'system'],
 ['who', 'can', 'be', 'a', 'minister', 'of', 'communion'],
 ['observing', 'brine', 'shrimp', 'under', 'a', 'microscope'],
 ['my', 'space.com', 'nancy'],
 ['background', 'history', 'and', 'success', 'stories', 'on', 'vegans'],
 ['conservation', 'of', 'natural', 'resources'],
 ['proverbs', '3', '5'],
 ['livonia', 'chamber', 'of', 'commerce'],
 ['skilled', 'requirements', 'ppt', 'after', 'therapy', 'discharge'],
 ['whittier', 'wood', 'products'],
 ['web', 'advisor', 'for', 'lmc'],
 ['silver', 'dollar', 'city'],
 ['attorneys', 'in', 'alexandria', 'louisiana'],
 ['free', 'adult', 'e-mail', 'animated'],
 ['tampa', 'florida', 'news'],
 ['how',
  'do',
  'u',
  'delete',
  'you',
  'message',
  'me',
  'block',
  'me',
  'thinging'],
 ['follies', 'palm', 'springs'],
 ['mt.', 'vernon', 'inn', 'ohio'],
 ['letter', 'from', 'hell'],
 ['katie', 'holmes', 'mi', 'iii', 'premiere'],
 ['cort', 'rental', 'furniture'],
 ['trouble', 'shoot', '2', 'stroke', '49cc', 'mini', 'chopper'],
 ['aarp', 'life', 'insurance'],
 ['racing', 'of', 'georgia', 'fast', 'co'],
 ['sprague', 'high', 'school', 'salem', 'oregon'],
 ['southwest', 'community', 'college', 'tn'],
 ['walt', 'disney', 'world'],
 ['soccer', 'world', 'cup'],
 ['texas', 'christian', 'university'],
 ['pepper', 'tree', 'campground', 'in', 'saint', 'augustine', 'florida'],
 ['hurrican', 'katrina', 'pictures'],
 ['aa.comhttp',
  'images.google.com',
  'images',
  'q',
  'thalia&svnum',
  '10&hl',
  'en&lr',
  '&ie',
  'utf-8&start',
  '180&sa',
  'n'],
 ['schott', 'body', 'panels'],
 ['fort', 'collins', 'co'],
 ['motocross', 'jorge', 'el', 'paso'],
 ['online', 'free', 'math', 'game'],
 ['live', 'aerial', 'vidio', 'of', 'beaumont', 'texas'],
 ['what', 'planet', 'is', 'tilted', 'on', 'its', 'side'],
 ['breakfast', 'buffets', 'in', 'buffalo', 'to', 'eat'],
 ['population', 'by', 'state'],
 ['pictures', 'of', 'dungeons'],
 ['texas', 'association', 'of', 'private', 'and', 'parochial', 'schools'],
 ['diy', 'top', '50', 'retailers'],
 ['www.zooye', '101', '.com'],
 ['free', 'west', 'va.', 'background', 'check'],
 ['how', 'to', 'kill', 'oneself', 'by', 'over', 'dosing', 'witn', 'insulin'],
 ['how', 'to', 'barbeque', 'chicken'],
 ['april', '2006', 'forecast'],
 ['palm', 'springs', 'movie', 'theaters'],
 ['aol', 'high', 'speed', 'internet'],
 ['nobody', 'knows', 'it', 'but', 'me', 'lyrics'],
 ['2003', 'honda', 'accord'],
 ['bradfordwhite', 'water', 'heater'],
 ['adams', 'county', 'colorado', 'dump'],
 ['city', 'of', 'boisie'],
 ['gun', 'store', 'fort', 'lee', 'new', 'jersey'],
 ['travis', 'boating', 'in', 'bossier', 'city'],
 ['treasure', 'house', 'jewelry'],
 ['pictures',
  'of',
  'animals',
  'that',
  'have',
  'been',
  'experimented',
  'on',
  'medically'],
 ['repo', 'homes', 'in', 'south', 'carolina'],
 ['www', 'myspace', 'com'],
 ['colonial', 'motel', 'doylestown', 'pennsylvania'],
 ['www.mbs', 'love', '.com'],
 ['jack',
  'greene',
  'honey',
  'i',
  'miss',
  'you',
  'and',
  "i'm",
  'being',
  'good',
  'and',
  "i'd"],
 ['ratings', 'on', 'alan', 'white', 'furniture'],
 ['f', 'a', 'davis', 'publishing'],
 ['free', 'medical', 'work', 'from', 'home'],
 ['power', 'custom', 'gunparts'],
 ['kid', 'reality', 'show', 'games'],
 ['got2b', 'hair', 'gel'],
 ['tool', 'bar', 'setings'],
 ['ralph', 'mabry', 'union', 'boss'],
 ['number', 'of', 'lawyers', 'in', 'florida'],
 ['the', 'youth', 'fair'],
 ['israel', 'national', 'radio'],
 ['general', 'liability', 'insurance'],
 ['celebrity', 'movie', 'archive'],
 ['chrevolet', 'car', 'renrals'],
 ['pep', 'boys', 'mail', 'creditcard', 'payment', 'where'],
 ['the', 'locations', 'of', 'pokemon', 'in', 'pokemon', 'silver'],
 ['continuing', 'education', 'for', 'cna', 'ca'],
 ['tyra', 'banks', 'show'],
 ['bunka', 'sai', 'torrance', '2006'],
 ['beverly', 'health', 'care'],
 ['if', 'you', 'can', 'dream', 'lyrics', 'by', 'ashley', 'gearing'],
 ['icicle', 'medication', 'for', "crohn's", 'disease'],
 ['sahara', 'motel', 'ocean', 'city', 'md'],
 ['anderson', 'honda', 'md'],
 ['nextel',
  'cell',
  'phones',
  'i',
  'want',
  'to',
  'buy',
  'with',
  'no',
  'plan',
  'phone',
  'only'],
 ['my', 'space', 'com'],
 ['american', 'standard', 'tank', 'lid', '4049'],
 ['any', 'calories', 'in', 'celery'],
 ['theglobe', 'and', 'mail.com'],
 ['types', 'of', 'sanwiches'],
 ['free', 'lesbian', 'sex', 'videos'],
 ['studying', 'for', 'writing', 'colleges'],
 ['www.', 'union', 'pacific', 'com.'],
 ['the', 'silver', 'fox', 'steakhouse', 'and', 'tx'],
 ['milford', 'pa.', 'school', 'district'],
 ['treasure', 'island', 'putt', 'putt'],
 ['marina', 'ruched', 'deep-v', 'top'],
 ['sierra', 'north', 'valley', 'mls'],
 ['heart', 'of', 'darkness', 'irony', 'ambiguity'],
 ['wwe', 'raw', 'archives', 'from', '2002-2005'],
 ['jobs', 'in', 'ohio'],
 ['viv', 'thomas', 'sisters', 'trailer'],
 ['blood', 'farm', 'groton', 'ma'],
 ['the', 'decatur', 'daily'],
 ['big', 'cum', 'swallow.com'],
 ['marion', 'on', 'line'],
 ['squirrels', 'that', 'resemble', 'racoons'],
 ['www.labor', 'state.', 'ny.', 'us'],
 ['affordable', 'teen', 'clothes'],
 ['pizza', 'places', 'in', 'goleta', 'ca'],
 ['bedding', 'for', 'a', 'guinea', 'pig'],
 ['idaho', 'dept', 'of', 'labor'],
 ['black', 'gay', 'clubs', 'in', 'miami'],
 ['2003', 'ford', 'f-150'],
 ['similar', 'property', 'value'],
 ['us', 'senate', 'idaho'],
 ['the', 'girl', 'is', 'mine', 'remix'],
 ['do', 'black', 'widows', 'live', 'in', 'washington'],
 ['scrawlings', 'in', 'the', 'dark'],
 ['laek', 'mead', 'state', 'park', 'nevada'],
 ['hotel', 'boca', 'raton'],
 ['advanced', 'prostodontics', 'books'],
 ['do', 'offset', 'drivers', 'work'],
 ['super', '1', 'grocery'],
 ['new', 'york', 'city', 'taxidermy'],
 ['please', 'bang', 'my', 'wife.com'],
 ['dick', 'van', 'dyke', 'movies'],
 ['las', 'vegas', 'acts', 'and', 'conventions'],
 ['does',
  'swanson',
  'chicken',
  'broth',
  'have',
  'to',
  'be',
  'heated',
  'before',
  'use'],
 ['actor', 'george', 'stanford', 'brown'],
 ['theravada', 'and', 'mahayana'],
 ['choreographed', 'cheer', 'camps', '&', 'clinics'],
 ['the', 'thirteenth', 'year.com'],
 ['runaway', 'slaves', 'and', 'norfolk', 'and', 'virginia'],
 ['granite', 'city', 'tool'],
 ['florida', 'paranormal', 'society'],
 ['the', 'battle', 'of', 'the', 'atlantic'],
 ['flying', 'hills', '.', 'reading', 'pa.'],
 ['brides', 'in', 'the', 'usa'],
 ['the', 'idaho', 'statesman'],
 ['yeide', 's', 'deli', 'morris', 'ave', 'union', 'nj'],
 ['pictures', 'of', '1932', '3', 'window', 'coupe'],
 ['ventana', 'canyon', 'resort'],
 ['warrens', 'water', 'park'],
 ['the', 'room', 'source.com'],
 ['mike', 'heren', 'fall', 'river'],
 ['cruise', 'ship', 'sickness'],
 ['union', 'la', 'grand', 'reopening'],
 ['bridle', 'and', 'bit', 'for', 'tennesse', 'walkers'],
 ['cape', 'fear', 'real', 'estate.com'],
 ['paint', 'show', 'secretary'],
 ['steve', 'and', 'barrys'],
 ['amtark', 'fare', 'and', 'schedule', 'in', 'tacoma', 'wa'],
 ['us', 'passport', 'renewel'],
 ['west', 'va', 'weather'],
 ['rockwood', 'reservation', 'and', 'range'],
 ['u', 's', 'bankruptcy', 'court'],
 ['whole', 'sale', "dvd's"],
 ['metropolitan', 'museum', 'of', 'art'],
 ['what',
  'form',
  'of',
  'execution',
  'was',
  'first',
  'used',
  'in',
  'the',
  'united',
  'states',
  'in',
  '1982'],
 ['http', 'www.lindsay', 'kormen'],
 ['real', 'estate', 'investing'],
 ['lyrics.',
  'eyes',
  'that',
  'i',
  'cant',
  'hidetheres',
  'a',
  'secret',
  'world',
  'inside',
  'of',
  'me',
  'that',
  'you',
  'may',
  'never',
  'see'],
 ['sterile', 'blood', 'infusion', 'sets'],
 ['xtreme', 'sports', 'colorado'],
 ['help', 'with', 'gas'],
 ['stephen', 'king', 'hells', 'angeles', 'mongals'],
 ['national', 'register', 'listings', 'in', 'florida'],
 ['gothic', 'clubs', 'orlando'],
 ['university', 'of', 'dayton'],
 ['central', 'carolina', 'bank'],
 ['dating', 'world', 'magazine'],
 ['stomach', 'pain', 'light', 'colored', 'stool'],
 ['akon', '2pac', 'big', 'ghetto'],
 ['summary', 'of', 'beatrice', 'in', 'much', 'ado', 'about', 'nothing'],
 ['broward', 'county', 'records'],
 ['japanese',
  'ladies',
  'having',
  'sex',
  'in',
  'pantyhose',
  'and',
  'stockings'],
 ['my', 'wife', 'panties', 'watched', 'resist'],
 ['nyc', 'dept', 'of', 'bldgs'],
 ['bellvue', 'wa', 'area', 'code'],
 ['map', 'of', 'kentucky'],
 ['university', 'of', 'utah'],
 ['holiday', 'inn', 'ft', 'lauderdale', 'beach', 'florida'],
 ['large', 'capacity', 'washing', 'machine', 'without', 'central', 'agitator'],
 ['the', 'delphian', 'school'],
 ['river', 'city', 'gymnastics', 'little', 'rock'],
 ['bobby', 'valentino', 'tell', 'me', 'lyrics'],
 ['www.world', '20powerliftig', '20', 'congress', '20.com'],
 ['charles', 'david', 'chandler'],
 ['2005', 'starting', 'pay', 'for', 'chp', 'cadets'],
 ['www.constructionwork', 'for', 'excons.con'],
 ['absolutley', 'free', 'porn', 'no', 'credit', 'card', 'needed'],
 ['the', 'dove', 'self-esteem', 'fund'],
 ['lloyd', 'banks', 'the', 'big', 'withdraw', 'advance'],
 ['ti', 'clifford', 'harris', 'birthday'],
 ['college', 'wrestling', 'ncaa', 'championsips'],
 ['poached', 'egg', 'recipes'],
 ['mrs', 'wishy', 'washy', 'coloring', 'pages'],
 ['amex', 'bema', 'gold'],
 ['free', 'online', 'driver', 'licence', 'maker'],
 ['cathedral', 'stained', 'glass', 'in', 'lafayette'],
 ['big', 'bouquet', 'of', 'roses'],
 ['default', 'anatomically', 'correct', 'sims', '2'],
 ['virus', '20', '20invitation'],
 ['little', 'league', 'baseball'],
 ['vanna', 'white', 'abc.com'],
 ['golf', 'courses', 'maryland'],
 ['a', 'picture', 'of', 'cecily', "tynan's", 'baby', 'boy', 'luke'],
 ['http', 'maxine', 'quotes.com'],
 ['salem', 'love', 'spells.com'],
 ['hotels', 'in', 'salem', 'ma.'],
 ['buckethead', 'finger', 'taping', 'with', 'three', 'fingers'],
 ['baltimore', 'jewish', 'times'],
 ['bars', 'lounges', 'taverns', 'prescott', 'area', 'arizona'],
 ['norma', 'jean', 'shaunluu', 'lyrics'],
 ['pima', 'community', 'college'],
 ['symantec', 'custmer', 'service'],
 ['cincinnati', 'christian', 'schools'],
 ['club', 'pogo', '.com'],
 ['accidents', 'in', 'louiville', 'kentucky', 'on', 'april', '21', '2006'],
 ['oklahoma', 'free', 'clinics'],
 ['become', 'a', 'flight', 'attendant'],
 ['hatfield', 'and', 'mccoy', 'cabins'],
 ['miami', 'county', 'clerk', 'of', 'court', 'ohoi'],
 ['new', 'construction', 'houses', 'in', 'brooklyn', '11236'],
 ['boulder', 'station', 'casino', 'job', 'search'],
 ['summary', 'of', 'the', 'war', 'of', '1812'],
 ['tampa', 'car', 'rentals'],
 ['bad', 'day', 'daniel', 'powter'],
 ['free', 'birthday', 'greetings'],
 ['old', 'lady', 'locks', 'toes', 'on', 'monster', 'cock'],
 ['milk', 'allergies', 'and', 'respiatory', 'problems'],
 ['math', 'work', 'for', '6th', 'grade'],
 ['sussex', 'county', 'nj', 'court'],
 ['lyrics', 'george', 'strait'],
 ['american', 'heart', 'association'],
 ['kevin', 'white', 'san', 'franacisco'],
 ["jack's", 'oyster', 'house'],
 ['how', 'to', 'invest', 'in', 'stocks', 'on', 'the', 'internet'],
 ['make', 'a', 'game', 'free'],
 ['risk', 'of', 'tummy', 'tucks'],
 ['pre', 'teen', 'tits'],
 ['david', 'allen', 'coe', 'underground', 'album'],
 ['listen', 'to', 'who', 'says', 'you', "can't", 'go', 'home'],
 ['air', 'conditioning', 'freon', 'restrictions'],
 ['digetal', 'camara', 'for', '50'],
 ['http', 'perfect', 'match.com'],
 ['world', 'war', '2', 'sub-machine', 'guns'],
 ['http',
  'www.gapgolf.comtype',
  'aol',
  'keywords',
  'or',
  'web',
  'addresses',
  'here'],
 ['ateamz.active.com', 'drbr', '.'],
 ['wwwmotor', 'home', 'chinook.com'],
 ['octagon', 'fish', 'tanks'],
 ['young', 'children', 'loosing', 'a', 'parent'],
 ['www.babies', 'r', 'us.com'],
 ['callousy', 'bump', 'on', 'palm'],
 ['simon', 'cowell', 'predictions', 'american', 'idol', '2006'],
 ['used', 'fire', 'trucks'],
 ['world', 'war', '2'],
 ['panic', 'at', 'the', 'disco'],
 ['fidelit', 'capital', 'and', 'income', 'fund'],
 ['http', 'www.citizensfla.com', 'assessment.cfm.'],
 ['jeep', 'grand', 'cherokee', 'manual'],
 ['guest', 'stars', 'on', 'lost'],
 ['full', 'hysterectomy', 'pros', 'and', 'cons'],
 ['all', 'rental', 'car', 'in', 'houston', 'lobby', 'airport'],
 ['hubble', 'space', 'telescope'],
 ['ohio', 'tax', 'refun', 'status'],
 ['city', 'gym', 'riverside'],
 ['social', 'security', 'death', 'index'],
 ['sliced', 'lemons', 'limes', 'and', 'oranges'],
 ['qci', 'projects', 'polk', 'county', 'florida'],
 ['indiana', 'unclaimed', 'money.com'],
 ['bankson', 'language', 'test', 'blt-2'],
 ['the', 'liberator', 'newspaper'],
 ['fraziers', 'farm', 'brooksville', 'fl'],
 ['organic', 'mixed', 'greens', 'new', 'chapter'],
 ['southwestern', 'college', 'chula', 'vista'],
 ['bridal', 'shower', 'games'],
 ['real', 'estate', 'one', 'indian', 'river', 'michigan'],
 ['whitney', 'houston-i', 'believe', 'in', 'you', 'and', 'me'],
 ['rainbow', 'music', 'productions'],
 ['lyrics',
  'sometimes',
  'i',
  'think',
  'about',
  'you',
  'walkin',
  'down',
  'the',
  'street',
  'and',
  'i',
  'believe',
  'it',
  'sometimes',
  'i',
  'think',
  'i',
  'see',
  'you',
  'lookin',
  'back',
  'at',
  'me'],
 ['80s', 'rock', 'love', 'songs'],
 ['wisconsin', 'girls', 'basketball'],
 ['bed', 'bath', 'and', 'beyond'],
 ['road', 'house', 'reels', 'online', 'casino'],
 ['st.', 'johns', 'bay', 'clothing'],
 ['institute', 'of', 'hawaiian', 'music', 'and', 'culture'],
 ['barnes', 'and', 'nobles.com'],
 ['http', 'hwww.sinco', 'demayo.orgrg'],
 ['day', 'spas', 'in', 'riverside', 'county', 'ca'],
 ['my', 'space', 'greg', 'lato'],
 ['computer', '20check', '20up'],
 ['alex', 'haley', 'pictures'],
 ['centennial', 'school', 'district.org'],
 ['msn', 'yellow', 'pages'],
 ['beachfront', 'rental', 'homes', 'florida'],
 ['okla', 'state', 'university'],
 ['jodawn', 'marie', 'green'],
 ['dunewood', 'and', 'fair', 'harbor', 'ferry', 'schedule'],
 ['united', 'ticket', 'centers'],
 ['what', 'are', 'volcanoes'],
 ['lyrics',
  'ooh',
  'ooh',
  'ooh',
  'baby',
  'baby',
  'linda',
  'ronstandt',
  'or',
  'smokey',
  'robinson'],
 ['san', 'bernardino', 'county'],
 ['unersity', 'of', 'chicago'],
 ['king', 'county', 'journal'],
 ['air', 'conditioning', 'union'],
 ['the', '7th', 'chakra'],
 ['romantic', 'espionage', 'brook', 'parrot', 'lyrics'],
 ['my', 'kitchen', 'witch', 'monmouth', 'beach', 'nj'],
 ['the',
  'college',
  'of',
  'new',
  'jersey',
  'missing',
  'student',
  'john',
  'fiocco'],
 ['planned', 'parenthood', 'of', 'mass'],
 ['http', 'black', 'america', 'web.com'],
 ['fl', 'juvenile', 'boot', 'camps'],
 ['jewish', 'actress', 'on', 'television'],
 ['the', 'arlington', 'hot', 'springs'],
 ['dave', 'and', 'barrys'],
 ['web', 'based', 'calendar'],
 ['mother', 'in', 'law', 'sex'],
 ['caffeine', 'and', 'belly', 'fat'],
 ['uw', 'green', 'bay'],
 ['http', 'college', 'board.com'],
 ['bartok', 'music', 'for', 'strings', 'percussionand', 'celesta'],
 ['news', 'paper', 'for', 'philadelphia'],
 ["alaska's", 'first', 'governor'],
 ['diet', 'pills', 'bonril'],
 ['aol', 'greeting', 'cards'],
 ['yeah', 'yeah', 'yeahs', 'gold', 'lion'],
 ['committee', 'on', 'government', 'reform'],
 ['dinsey', 'online', 'kids', 'games'],
 ['top', 'rated', "girl's", 'fast', 'pitch', 'softball', 'bats'],
 ['latter', 'days', 'gay'],
 ['collection', 'agency', 'jobs', 'in', 'birmingham'],
 ['jordans', 'furniture', 'retail', 'services'],
 ['city', 'of', 'atlanta', 'careers'],
 ['only', 'sixteen', 'what', 'kind', 'og', 'curfew', 'is', 'at', 'ten', 'pm'],
 ['university', 'of', 'miami', 'psychological', 'testing'],
 ['anthony', 'tassone', 'ewing', 'nj'],
 ['how', 'many', 'time', 'zones', 'are', 'there'],
 ['walking', 'cane', 'tree'],
 ['dr.', 'gene', 'velasco', 'in', 'minnesota'],
 ["where's", 'my', 'return'],
 ['george', 'straight', 'album'],
 ['paramount', 'theater', 'box', 'office'],
 ['riversend', 'free', 'e-cards'],
 ['pa', 'carrer', 'link'],
 ['big', 'truck', 'parts'],
 ['condos', 'at', 'lamkin', 'in', 'pueblo', 'colorado'],
 ['doha', 'and', 'qatar'],
 ['new', 'york', 'ocse'],
 ['white', 'rogers', 'heat', 'air', 'condition', 'controller'],
 ['honda', 'of', 'troy'],
 ['public', 'education', 'in', 'bogota', 'colombia'],
 ['club', 'fathom', 'chattanooga'],
 ['animal', 'humane', 'society'],
 ['aol', 'sign', 'in', 'screen'],
 ['map', 'of', 'the', 'united', 'states', 'of', 'america'],
 ['magazine', 'second', 'hands', 'in', 'miami'],
 ['you', 'cant', 'stop', 'this', 'feeling'],
 ['bar', 'restaurant', 'with', 'property', 'for', 'sale', 'n.y.'],
 ['horse', 'in', 'the', 'preakness'],
 ['1929', 'cookeville', 'tennessee', 'water', 'supply'],
 ['how', 'to', 'grow', 'roses'],
 ['how', 'to', 'make', 'a', 'duvet', 'cover'],
 ['setting', 'an', 'email', 'address'],
 ['cottage', 'style', 'furniture'],
 ['mcgaw', 'ymca', 'camp', 'echo'],
 ['http',
  'ww2.potterybarn.com',
  'cat',
  'pippopup.cfm',
  'gids',
  'p3516&skus',
  '&cat',
  '&type',
  'relateditems&lid',
  '65536&page',
  '1&src',
  'pipaprw',
  'cthmotx',
  'gp3516',
  'k',
  'nshop',
  'rgift',
  'thm',
  's'],

In [97]:
df_cols=list(df.columns.values)
print(df_cols)
df_cols.remove("UserId")
df_cols.remove("Query")

['UserId', 'Query', 'horse', 'http', 'photos', 'in', 'a', 'up', 'the', 'company', 'grand', 'michigan', 'truck', 'rental', 'back', 'to', 'blue', 'business', 'services', 'national', 'real', 'estate', 'pennsylvania', 'and', 'first', 'american', 'united', 'one', 'credit', 'group', 'security', 'search', 'of', 'auto', 'kentucky', 'green', 'state', 'university', 'black', 'orange', 'home', 'page', 'david', 'college', 'dog', 'honda', 'light', 'pa', 'off', 'make', 'house', 'us', 'center', 'philadelphia', 'art', 'museum', 'mall', 'child', 'when', 'b', 'at', 'zip', 'codes', 'movie', 'il', 'illinois', 'theater', 'valley', 'girls', 'be', 'schedule', 'war', 'guide', 'with', 'car', 'cards', 'number', 'for', 'bank', 'america', 'georgia', 'texas', 'county', 'n', 'bed', 'bath', 'fort', 'birthday', 'party', 'baby', 'rent', 'medical', 'kids', 'how', 'online', 'virginia', 'is', 'it', 'r', 'atlanta', 'ga', 'christian', 'summer', 'camp', 'washington', 'george', 'oil', 'care', 'north', 'springs', 'high', 'school', 'death', 'st', 'parts', 'j', 'c', 'from', 'computer', 'new', 'creek', 'association', 'city', 'park', 'best', 'money', 'year', 'body', 'water', 'tv', 'show', 'clothing', 'store', 'game', 'free', 'children', 'who', 'have', 'aol', 'me', 'women', 'on', '.', 'cruise', 'people', 'pictures', 'social', 'board', 'public', 'my', 'small', 'disney', 'line', 'club', 'blood', 'song', 'lyrics', 'you', 'recipes', 'world', 'cheap', 'songs', 'about', 'john', 'vegas', 'king', 'time', 'by', 'work', 'out', 'little', 'rock', 'district', 'gay', 'play', 'florida', 'department', 'palm', 'beach', 'miami', 'court', 'hospital', 'deal', 'or', 'no', 'sports', 'community', 'bar', 'law', 'family', 'island', 'union', 'band', 'lottery', 'de', 'la', 'south', 'mary', 'society', 'area', 'code', 'property', 'web', 'site', 'golf', 'sun', 'news', 'paper', 'post', 'times', 'sales', 'schools', 'west', 'police', 'fishing', 'radio', 'wall', 'www.', 'com', '2', 'middle', '.com', '2005', 'east', 'map', 'road', 'big', 'silver', 'point', 'gold', 'mobile', 'men', 'power', 'where', 'love', 'i', 'boys', 'town', 'country', 'list', 'color', 'day', 'history', 'channel', 'english', 'wood', 'that', 'river', 'york', 'bay', 'ny', 'man', 'long', 'sexy', 'states', 'california', 'garden', 'training', 'shop', 'san', 'was', 'quotes', 'heart', 'sale', 'lake', 'parks', 'mountain', 'kelly', 'book', 'weight', 'report', '2006', 'your', 'download', 'casino', 'tax', 'oregon', 'job', 'ca', '&', 'health', 'food', 'dr.', 'md', 'are', 'not', 'music', 'thomas', 'myspace', 'what', '1', '3', 'gas', 'st.', 'does', 'night', 'live', 'life', 'pics', 'games', 'boy', 'all', 'fish', 'street', '4', 'sites', 'ohio', 'size', 'pages', 'rentals', 'travel', 'resort', 'over', 'hotels', 'inn', 'hotel', '-', 'help', 'support', 'daily', 'cars', 'service', 'maryland', 'dresses', 'old', 'red', 'nyc', 'system', 'can', 'after', 'white', 'do', 'phone', 'cancer', 'tickets', 'jobs', 'low', 'las', 'los', 'angeles', 'hot', 'homes', 'wedding', '10', 'fire', 'nursing', 'diego', 'church', 'central', 'as', 'yellow', 'realty', 'card', 'usa', 'houses', 'wholesale', 'pool', 'baseball', 'air', 'office', 'co', 'bill', 'fl', 'weather', 'forms', 'chicago', 'get', 'girl', 'like', 't', 'internet', 'brown', 'spanish', 'sex', 'stores', '5', 'restaurant', 'animal', 'results', 'video', 'space', 'carolina', 'star', 'good', 'teen', 'dvd', 'dance', 'photo', 'hair', 'library', 'recipe', 'shoes', 'cell', 'adult', 'western', 'dallas', 'picture', 'airport', 'boston', 'model', 'ma', 'price', 'colorado', 'tx', 'wild', 'science', 'orlando', 'buy', 'cd', 'cheats', 'insurance', 'furniture', 'movies', 'magazine', 'address', 'international', '20', 'young', 'james', 'va', 'ford', 'website', 'cross', 'videos', 'screen', 'names', 'alabama', 'dogs', 'diet', 'mexico', 'clubs', 'e', 'go', 'products', 'mi', 'license', 'apartments', 'inc', 'el', 'y', 'bad', 'sc', 'records', 'tour', 'jersey', 'nj', 'dept', 's', 'motor', 'nude', 'nc', 'downloads', 'an', 'great', 'education', 'oklahoma', '8', 'land', 'head', 'porn', 'naked', 'program', 'general', 'southern', 'hill', 'used', 'arizona', 'employment', 'room', 'discount', 'ice', 'find', 'this', 'books', 'review', 'indiana', 'name', 'top', 'federal', 'tampa', 'information', 'tree', 'ky', 'basketball', 'newspaper', 'www', 'down', 'massachusetts', 'if', 'will', 'plans', 'ct', 'houston', 'why', 'yahoo', 'louis', 'tn', 'maine', 'test', 'local', 'tennessee', 'santa']

In [98]:
for col in df_cols:  # Loop through column names
    df[col] = df[col].apply(lambda x: 0 if x == 'f' else 1)

In [99]:
number_occured= {

}
for col in df_cols:
    print(col)
    res=(df[col].values==1).sum()
    number_occured[f"{col}"]=f'{res}'
number_occured

horse
http
photos
in
a
up
the
company
grand
michigan
truck
rental
back
to
blue
business
services
national
real
estate
pennsylvania
and
first
american
united
one
credit
group
security
search
of
auto
kentucky
green
state
university
black
orange
home
page
david
college
dog
honda
light
pa
off
make
house
us
center
philadelphia
art
museum
mall
child
when
b
at
zip
codes
movie
il
illinois
theater
valley
girls
be
schedule
war
guide
with
car
cards
number
for
bank
america
georgia
texas
county
n
bed
bath
fort
birthday
party
baby
rent
medical
kids
how
online
virginia
is
it
r
atlanta
ga
christian
summer
camp
washington
george
oil
care
north
springs
high
school
death
st
parts
j
c
from
computer
new
creek
association
city
park
best
money
year
body
water
tv
show
clothing
store
game
free
children
who
have
aol
me
women
on
.
cruise
people
pictures
social
board
public
my
small
disney
line
club
blood
song
lyrics
you
recipes
world
cheap
songs
about
john
vegas
king
time
by
work
out
little
rock
district
gay
play
florida
department
palm
beach
miami
court
hospital
deal
or
no
sports
community
bar
law
family
island
union
band
lottery
de
la
south
mary
society
area
code
property
web
site
golf
sun
news
paper
post
times
sales
schools
west
police
fishing
radio
wall
www.
com
2
middle
.com
2005
east
map
road
big
silver
point
gold
mobile
men
power
where
love
i
boys
town
country
list
color
day
history
channel
english
wood
that
river
york
bay
ny
man
long
sexy
states
california
garden
training
shop
san
was
quotes
heart
sale
lake
parks
mountain
kelly
book
weight
report
2006
your
download
casino
tax
oregon
job
ca
&
health
food
dr.
md
are
not
music
thomas
myspace
what
1
3
gas
st.
does
night
live
life
pics
games
boy
all
fish
street
4
sites
ohio
size
pages
rentals
travel
resort
over
hotels
inn
hotel
-
help
support
daily
cars
service
maryland
dresses
old
red
nyc
system
can
after
white
do
phone
cancer
tickets
jobs
low
las
los
angeles
hot
homes
wedding
10
fire
nursing
diego
church
central
as
yellow
realty
card
usa
houses
wholesale
pool
baseball
air
office
co
bill
fl
weather
forms
chicago
get
girl
like
t
internet
brown
spanish
sex
stores
5
restaurant
animal
results
video
space
carolina
star
good
teen
dvd
dance
photo
hair
library
recipe
shoes
cell
adult
western
dallas
picture
airport
boston
model
ma
price
colorado
tx
wild
science
orlando
buy
cd
cheats
insurance
furniture
movies
magazine
address
international
20
young
james
va
ford
website
cross
videos
screen
names
alabama
dogs
diet
mexico
clubs
e
go
products
mi
license
apartments
inc
el
y
bad
sc
records
tour
jersey
nj
dept
s
motor
nude
nc
downloads
an
great
education
oklahoma
8
land
head
porn
naked
program
general
southern
hill
used
arizona
employment
room
discount
ice
find
this
books
review
indiana
name
top
federal
tampa
information
tree
ky
basketball
newspaper
www
down
massachusetts
if
will
plans
ct
houston
why
yahoo
louis
tn
maine
test
local
tennessee
santa

{'horse': '17',
 'http': '216',
 'photos': '31',
 'in': '830',
 'a': '319',
 'up': '42',
 'the': '659',
 'company': '42',
 'grand': '21',
 'michigan': '49',
 'truck': '18',
 'rental': '33',
 'back': '17',
 'to': '398',
 'blue': '43',
 'business': '31',
 'services': '20',
 'national': '45',
 'real': '70',
 'estate': '60',
 'pennsylvania': '25',
 'and': '519',
 'first': '30',
 'american': '87',
 'united': '35',
 'one': '46',
 'credit': '61',
 'group': '23',
 'security': '21',
 'search': '35',
 'of': '927',
 'auto': '41',
 'kentucky': '18',
 'green': '26',
 'state': '123',
 'university': '77',
 'black': '64',
 'orange': '20',
 'home': '113',
 'page': '19',
 'david': '24',
 'college': '80',
 'dog': '38',
 'honda': '20',
 'light': '17',
 'pa': '50',
 'off': '21',
 'make': '40',
 'house': '57',
 'us': '37',
 'center': '78',
 'philadelphia': '16',
 'art': '37',
 'museum': '16',
 'mall': '12',
 'child': '29',
 'when': '19',
 'b': '10',
 'at': '88',
 'zip': '10',
 'codes': '25',
 'movie': '48',
 'il': '14',
 'illinois': '26',
 'theater': '14',
 'valley': '32',
 'girls': '50',
 'be': '35',
 'schedule': '11',
 'war': '28',
 'guide': '11',
 'with': '102',
 'car': '79',
 'cards': '34',
 'number': '36',
 'for': '547',
 'bank': '49',
 'america': '29',
 'georgia': '35',
 'texas': '77',
 'county': '235',
 'n': '18',
 'bed': '18',
 'bath': '14',
 'fort': '26',
 'birthday': '17',
 'party': '25',
 'baby': '29',
 'rent': '31',
 'medical': '34',
 'kids': '30',
 'how': '177',
 'online': '70',
 'virginia': '57',
 'is': '114',
 'it': '48',
 'r': '19',
 'atlanta': '25',
 'ga': '26',
 'christian': '19',
 'summer': '14',
 'camp': '16',
 'washington': '40',
 'george': '15',
 'oil': '17',
 'care': '31',
 'north': '53',
 'springs': '25',
 'high': '101',
 'school': '154',
 'death': '17',
 'st': '49',
 'parts': '38',
 'j': '8',
 'c': '11',
 'from': '87',
 'computer': '21',
 'new': '218',
 'creek': '18',
 'association': '23',
 'city': '131',
 'park': '65',
 'best': '46',
 'money': '14',
 'year': '18',
 'body': '24',
 'water': '34',
 'tv': '30',
 'show': '38',
 'clothing': '23',
 'store': '46',
 'game': '38',
 'free': '224',
 'children': '23',
 'who': '35',
 'have': '26',
 'aol': '72',
 'me': '44',
 'women': '36',
 'on': '231',
 '.': '18',
 'cruise': '17',
 'people': '33',
 'pictures': '95',
 'social': '18',
 'board': '17',
 'public': '42',
 'my': '105',
 'small': '11',
 'disney': '20',
 'line': '41',
 'club': '68',
 'blood': '15',
 'song': '40',
 'lyrics': '175',
 'you': '102',
 'recipes': '21',
 'world': '57',
 'cheap': '30',
 'songs': '19',
 'about': '34',
 'john': '30',
 'vegas': '42',
 'king': '20',
 'time': '37',
 'by': '98',
 'work': '27',
 'out': '25',
 'little': '21',
 'rock': '19',
 'district': '27',
 'gay': '25',
 'play': '21',
 'florida': '136',
 'department': '51',
 'palm': '26',
 'beach': '87',
 'miami': '30',
 'court': '38',
 'hospital': '52',
 'deal': '8',
 'or': '43',
 'no': '23',
 'sports': '21',
 'community': '42',
 'bar': '18',
 'law': '20',
 'family': '26',
 'island': '47',
 'union': '39',
 'band': '14',
 'lottery': '15',
 'de': '44',
 'la': '41',
 'south': '45',
 'mary': '16',
 'society': '26',
 'area': '36',
 'code': '39',
 'property': '27',
 'web': '31',
 'site': '22',
 'golf': '33',
 'sun': '18',
 'news': '84',
 'paper': '14',
 'post': '20',
 'times': '23',
 'sales': '15',
 'schools': '42',
 'west': '41',
 'police': '20',
 'fishing': '14',
 'radio': '26',
 'wall': '7',
 'www.': '38',
 'com': '44',
 '2': '60',
 'middle': '18',
 '.com': '70',
 '2005': '20',
 'east': '23',
 'map': '45',
 'road': '20',
 'big': '32',
 'silver': '19',
 'point': '14',
 'gold': '23',
 'mobile': '14',
 'men': '17',
 'power': '23',
 'where': '24',
 'love': '33',
 'i': '98',
 'boys': '17',
 'town': '19',
 'country': '34',
 'list': '30',
 'color': '11',
 'day': '66',
 'history': '29',
 'channel': '18',
 'english': '13',
 'wood': '15',
 'that': '55',
 'river': '31',
 'york': '93',
 'bay': '24',
 'ny': '75',
 'man': '20',
 'long': '28',
 'sexy': '17',
 'states': '24',
 'california': '54',
 'garden': '13',
 'training': '16',
 'shop': '18',
 'san': '58',
 'was': '21',
 'quotes': '14',
 'heart': '20',
 'sale': '96',
 'lake': '48',
 'parks': '15',
 'mountain': '11',
 'kelly': '9',
 'book': '44',
 'weight': '23',
 'report': '12',
 '2006': '87',
 'your': '75',
 'download': '34',
 'casino': '12',
 'tax': '46',
 'oregon': '16',
 'job': '31',
 'ca': '36',
 '&': '82',
 'health': '36',
 'food': '28',
 'dr.': '18',
 'md': '23',
 'are': '40',
 'not': '27',
 'music': '60',
 'thomas': '17',
 'myspace': '40',
 'what': '128',
 '1': '28',
 '3': '25',
 'gas': '15',
 'st.': '38',
 'does': '31',
 'night': '16',
 'live': '22',
 'life': '32',
 'pics': '54',
 'games': '52',
 'boy': '20',
 'all': '37',
 'fish': '19',
 'street': '24',
 '4': '22',
 'sites': '18',
 'ohio': '70',
 'size': '13',
 'pages': '32',
 'rentals': '19',
 'travel': '12',
 'resort': '28',
 'over': '20',
 'hotels': '47',
 'inn': '39',
 'hotel': '55',
 '-': '32',
 'help': '23',
 'support': '10',
 'daily': '18',
 'cars': '20',
 'service': '32',
 'maryland': '27',
 'dresses': '9',
 'old': '47',
 'red': '34',
 'nyc': '15',
 'system': '24',
 'can': '37',
 'after': '16',
 'white': '46',
 'do': '60',
 'phone': '50',
 'cancer': '15',
 'tickets': '20',
 'jobs': '48',
 'low': '10',
 'las': '45',
 'los': '25',
 'angeles': '24',
 'hot': '37',
 'homes': '51',
 'wedding': '43',
 '10': '19',
 'fire': '16',
 'nursing': '17',
 'diego': '13',
 'church': '46',
 'central': '32',
 'as': '15',
 'yellow': '23',
 'realty': '20',
 'card': '25',
 'usa': '18',
 'houses': '19',
 'wholesale': '22',
 'pool': '17',
 'baseball': '27',
 'air': '44',
 'office': '36',
 'co': '19',
 'bill': '19',
 'fl': '36',
 'weather': '29',
 'forms': '8',
 'chicago': '49',
 'get': '34',
 'girl': '25',
 'like': '14',
 't': '14',
 'internet': '16',
 'brown': '19',
 'spanish': '20',
 'sex': '75',
 'stores': '19',
 '5': '25',
 'restaurant': '30',
 'animal': '17',
 'results': '8',
 'video': '32',
 'space': '21',
 'carolina': '43',
 'star': '25',
 'good': '20',
 'teen': '20',
 'dvd': '14',
 'dance': '17',
 'photo': '13',
 'hair': '32',
 'library': '26',
 'recipe': '16',
 'shoes': '11',
 'cell': '25',
 'adult': '26',
 'western': '12',
 'dallas': '17',
 'picture': '42',
 'airport': '23',
 'boston': '17',
 'model': '13',
 'ma': '27',
 'price': '11',
 'colorado': '31',
 'tx': '19',
 'wild': '21',
 'science': '15',
 'orlando': '23',
 'buy': '30',
 'cd': '7',
 'cheats': '20',
 'insurance': '31',
 'furniture': '32',
 'movies': '14',
 'magazine': '14',
 'address': '15',
 'international': '18',
 '20': '23',
 'young': '15',
 'james': '16',
 'va': '37',
 'ford': '29',
 'website': '15',
 'cross': '16',
 'videos': '16',
 'screen': '16',
 'names': '14',
 'alabama': '25',
 'dogs': '8',
 'diet': '12',
 'mexico': '24',
 'clubs': '15',
 'e': '26',
 'go': '21',
 'products': '23',
 'mi': '19',
 'license': '18',
 'apartments': '22',
 'inc': '13',
 'el': '16',
 'y': '12',
 'bad': '24',
 'sc': '21',
 'records': '25',
 'tour': '13',
 'jersey': '42',
 'nj': '40',
 'dept': '20',
 's': '24',
 'motor': '13',
 'nude': '29',
 'nc': '42',
 'downloads': '15',
 'an': '27',
 'great': '15',
 'education': '22',
 'oklahoma': '23',
 '8': '21',
 'land': '18',
 'head': '9',
 'porn': '27',
 'naked': '20',
 'program': '21',
 'general': '6',
 'southern': '15',
 'hill': '16',
 'used': '37',
 'arizona': '21',
 'employment': '14',
 'room': '23',
 'discount': '13',
 'ice': '21',
 'find': '18',
 'this': '21',
 'books': '18',
 'review': '10',
 'indiana': '30',
 'name': '28',
 'top': '27',
 'federal': '25',
 'tampa': '20',
 'information': '23',
 'tree': '18',
 'ky': '18',
 'basketball': '16',
 'newspaper': '20',
 'www': '30',
 'down': '13',
 'massachusetts': '14',
 'if': '19',
 'will': '23',
 'plans': '11',
 'ct': '15',
 'houston': '26',
 'why': '11',
 'yahoo': '19',
 'louis': '22',
 'tn': '12',
 'maine': '10',
 'test': '23',
 'local': '8',
 'tennessee': '12',
 'santa': '12'}

In [ ]:
df['Query'].apply(lambda x: x.split(" ")).to_list()

{('5',): 2, ('0', '5'): 2, ('1',): 2, ('e', 'i', 'z'): 2, ('a', 'e', 'i', 'z'): 2, ('a', 'e', 'z'): 2, ('n', 'z'): 2, ('a', 'n', 'z'): 4, ('i', 'n', 'z'): 2, ('a', 'i', 'n', 'z'): 2, ('i', 'z'): 4, ('a', 'z'): 4, ('a', 'i', 'z'): 4, ('a', 'a', 'z'): 2, ('a', 'a', 'i', 'z'): 2, ('2',): 4, ('0', '2'): 5, ('.',): 5, ('.', 'w'): 3, ('a', 'x'): 2, ('a', 't', 'x'): 2, ('t', 'x'): 3, ('s', 'x'): 3, ('e', 's', 'x'): 3, ('e', 'x'): 4, ('0',): 6, ('0', '0'): 2, ('j', 'n'): 2, ('b', 'j'): 2, ('b', 'j', 'o'): 2, ('j', 'o'): 3, ('j', 's'): 3, ('e', 'j'): 3, ('e', 'j', 's'): 3, ('c', 'r', 'v'): 2, ('c', 'r', 's', 'v'): 3, ('c', 'e', 'r', 'v'): 4, ('c', 'e', 'r', 's', 'v'): 3, ('c', 'i', 'r', 'v'): 2, ('c', 'i', 'r', 's', 'v'): 3, ('c', 'e', 'i', 'r', 'v'): 4, ('c', 'e', 'i', 'r', 's', 'v'): 3, ('c', 'i', 's', 'v'): 3, ('c', 'e', 'i', 's', 'v'): 6, ('c', 'e', 'i', 'v'): 4, ('c', 'e', 'e', 'i', 'v'): 2, ('c', 's', 'v'): 3, ('c', 'e', 's', 'v'): 6, ('c', 'e', 'v'): 4, ('c', 'e', 'e', 'v'): 2, ('m', 'v'): 2, ('m', 'o', 'v'): 2, ('i', 'm', 'v'): 2, ('e', 'm', 'v'): 2, ('i', 'm', 'o', 'v'): 2, ('e', 'm', 'o', 'v'): 2, ('e', 'i', 'm', 'v'): 2, ('e', 'i', 'm', 'o', 'v'): 2, ('a', 'g', 'v'): 2, ('a', 'g', 'i', 'v'): 3, ('g', 'i', 'v'): 3, ('g', 'i', 'i', 'v'): 3, ('e', 'i', 's', 'v', 'y'): 3, ('e', 'i', 'n', 's', 'v', 'y'): 5, ('e', 'n', 's', 'v', 'y'): 4, ('e', 'n', 'n', 's', 'v', 'y'): 3, ('a', 's', 'v', 'y'): 2, ('a', 'e', 's', 'v', 'y'): 2, ('a', 'i', 's', 'v', 'y'): 2, ('a', 'n', 's', 'v', 'y'): 6, ('a', 'e', 'i', 's', 'v', 'y'): 2, ('a', 'e', 'n', 's', 'v', 'y'): 2, ('a', 'i', 'n', 's', 'v', 'y'): 2, ('a', 'e', 'i', 'n', 's', 'v', 'y'): 2, ('i', 's', 'v', 'y'): 3, ('i', 'n', 's', 'v', 'y'): 5, ('n', 's', 'v', 'y'): 4, ('n', 'n', 's', 'v', 'y'): 3, ('l', 'v', 'y'): 3, ('l', 'n', 'v', 'y'): 3, ('a', 'l', 'v', 'y'): 4, ('a', 'l', 'n', 'v', 'y'): 6, ('a', 'n', 'v', 'y'): 6, ('a', 'n', 'n', 'v', 'y'): 6, ('i', 'v', 'y'): 3, ('a', 'i', 'v', 'y'): 2, ('i', 'n', 'v', 'y'): 5, ('a', 'i', 'n', 'v', 'y'): 2, ('e', 'i', 'v', 'y'): 3, ('e', 'i', 'n', 'v', 'y'): 5, ('a', 'e', 'v', 'y'): 3, ('a', 'e', 'i', 'v', 'y'): 2, ('a', 'e', 'n', 'v', 'y'): 6, ('a', 'e', 'i', 'n', 'v', 'y'): 2, ('e', 'l', 'v', 'y'): 3, ('a', 'e', 'l', 'v', 'y'): 4, ('e', 'l', 'n', 'v', 'y'): 3, ('a', 'e', 'l', 'n', 'v', 'y'): 3, ('e', 'n', 'v', 'y'): 4, ('e', 'n', 'n', 'v', 'y'): 3, ('n', 'v', 'y'): 4, ('n', 'n', 'v', 'y'): 3, ('r', 't', 'v'): 2, ('i', 't', 'v'): 2, ('i', 'r', 't', 'v'): 2, ('e', 'i', 't', 'v'): 2, ('e', 'r', 't', 'v'): 2, ('e', 'i', 'r', 't', 'v'): 2, ('n', 'r', 'v'): 2, ('i', 'n', 'r', 'v'): 5, ('e', 'l', 'n', 'v'): 3, ('a', 'e', 'l', 'n', 'v'): 6, ('e', 'l', 'n', 'n', 'v'): 3, ('a', 'e', 'l', 'n', 'n', 'v'): 3, ('l', 'n', 's', 'v'): 3, ('e', 'l', 'n', 's', 'v'): 3, ('a', 'l', 'n', 's', 'v'): 6, ('l', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'l', 'n', 's', 'v'): 3, ('e', 'l', 'n', 'n', 's', 'v'): 3, ('a', 'l', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'l', 'n', 'n', 's', 'v'): 3, ('i', 'l', 'n', 'v'): 3, ('i', 'l', 'n', 's', 'v'): 3, ('e', 'i', 'l', 'n', 'v'): 3, ('a', 'i', 'l', 'n', 'v'): 6, ('i', 'l', 'n', 'n', 'v'): 3, ('e', 'i', 'l', 'n', 's', 'v'): 3, ('a', 'i', 'l', 'n', 's', 'v'): 3, ('i', 'l', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'i', 'l', 'n', 'v'): 3, ('e', 'i', 'l', 'n', 'n', 'v'): 3, ('a', 'i', 'l', 'n', 'n', 'v'): 3, ('a', 'e', 'i', 'l', 'n', 's', 'v'): 3, ('e', 'i', 'l', 'n', 'n', 's', 'v'): 3, ('a', 'i', 'l', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'i', 'l', 'n', 'n', 'v'): 3, ('a', 'e', 'i', 'l', 'n', 'n', 's', 'v'): 3, ('l', 'n', 'n', 'v'): 3, ('a', 'l', 'n', 'n', 'v'): 6, ('a', 'l', 'n', 'v'): 6, ('a', 'a', 'l', 'n', 'v'): 3, ('n', 'n', 'v'): 3, ('e', 'n', 'n', 'v'): 3, ('n', 'n', 's', 'v'): 3, ('a', 'n', 'n', 'v'): 6, ('i', 'n', 'n', 'v'): 3, ('e', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'n', 'n', 'v'): 3, ('e', 'i', 'n', 'n', 'v'): 3, ('a', 'n', 'n', 's', 'v'): 3, ('i', 'n', 'n', 's', 'v'): 3, ('a', 'i', 'n', 'n', 'v'): 3, ('a', 'e', 'n', 'n', 's', 'v'): 3, ('e', 'i', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'i', 'n', 'n', 'v'): 3, ('a', 'i', 'n', 'n', 's', 'v'): 3, ('a', 'e', 'i', 'n', 'n', 's', 'v'): 3, ('i', 'n', 's', 'v'): 5, ('a', 'i', 'n', 's', 'v'): 6, ('a', 'n', 's', 'v'): 6, ('a', 'a', 'n', 's', 'v'): 3, ('e', 'i', 'n', 's', 'v'): 5, ('a', 'e', 'i', 'n', 's', 'v'): 6, ('a', 'e', 'n', 's', 'v'): 6, ('a', 'a', 'e', 'n', 's', 'v'): 3, ('e', 'i', 'n', 'v'): 5, ('a', 'e', 'i', 'n', 'v'): 6, ('a', 'e', 'n', 'v'): 6, ('a', 'a', 'e', 'n', 'v'): 3, ('a', 'a', 'n', 'v'): 3, ('a', 'a', 'i', 'n', 'v'): 3, ('a', 'i', 'n', 'v'): 9, ('a', 'i', 'i', 'n', 'v'): 3, ('i', 'n', 'v'): 8, ('i', 'i', 'n', 'v'): 4, ('a', 'd', 'v'): 2, ('a', 'd', 'i', 'v'): 2, ('d', 'd', 'v'): 2, ('d', 'e', 'v'): 2, ('d', 'e', 'i', 'v'): 2, ('d', 'i', 'v'): 4, ('d', 'o', 'v'): 2, ('d', 'i', 'o', 'v'): 2, ('d', 'e', 'o', 'v'): 2, ('d', 'e', 'i', 'o', 'v'): 2, ('o', 's', 'v'): 2, ('i', 'o', 's', 'v'): 2, ('e', 'o', 's', 'v'): 2, ('e', 'i', 'o', 's', 'v'): 2, ('i', 'o', 'v'): 4, ('e', 'i', 'o', 'v'): 4, ('e', 'o', 'v'): 6, ('i', 'l', 's', 'v'): 2, ('a', 'l', 's', 'v'): 2, ('a', 'i', 'l', 's', 'v'): 2, ('a', 'e', 'l', 's', 'v'): 2, ('e', 'i', 'l', 's', 'v'): 2, ('a', 'e', 'i', 'l', 's', 'v'): 2, ('l', 'r', 'v'): 2, ('e', 'l', 'r', 'v'): 2, ('i', 'l', 'v'): 3, ('a', 'i', 'l', 'v'): 2, ('e', 'i', 'l', 'v'): 3, ('a', 'e', 'i', 'l', 'v'): 2, ('a', 'l', 'v'): 5, ('a', 'e', 'l', 'v'): 5, ('e', 'l', 'v'): 7, ('i', 'r', 's', 'v'): 6, ('e', 'i', 'r', 's', 'v'): 9, ('e', 'r', 's', 'v'): 8, ('e', 'e', 'r', 's', 'v'): 3, ('i', 's', 'v'): 9, ('e', 'i', 's', 'v'): 12, ('e', 's', 'v'): 12, ('e', 'e', 's', 'v'): 3, ('a', 'r', 'v'): 2, ('a', 'i', 'r', 'v'): 3, ('a', 's', 'v'): 3, ('a', 'e', 's', 'v'): 3, ('a', 'i', 's', 'v'): 2, ('a', 'e', 'i', 's', 'v'): 2, ('a', 'i', 'v'): 6, ('a', 'i', 'i', 'v'): 3, ('a', 'e', 'v'): 6, ('a', 'e', 'i', 'v'): 2, ('i', 'i', 'r', 'v'): 4, ('e', 'i', 'r', 'v'): 11, ('e', 'e', 'i', 'r', 'v'): 3, ('e', 'r', 'v'): 12, ('e', 'e', 'r', 'v'): 3, ('i', 'i', 'v'): 4, ('e', 'i', 'v'): 16, ('e', 'e', 'i', 'v'): 3, ('e', 'v'): 21, ('e', 'e', 'v'): 3, ('k', 'm'): 2, ('a', 'k', 'm'): 3, ('k', 'm', 'o'): 2, ('a', 'k', 'm', 'o'): 2, ('d', 'k'): 2, ('k', 'p'): 2, ('k', 'p', 'r'): 2, ('a', 'k', 'p'): 2, ('a', 'k', 'p', 'r'): 2, ('k', 'u'): 3, ('k', 't', 'u'): 3, ('c', 'k', 'u'): 3, ('k', 'n', 'u'): 2, ('k', 'u', 'y'): 2, ('e', 'k', 'u'): 2, ('c', 'k', 't', 'u'): 3, ('k', 'n', 't', 'u'): 2, ('k', 't', 'u', 'y'): 2, ('e', 'k', 't', 'u'): 2, ('c', 'k', 'n', 'u'): 2, ('c', 'k', 'u', 'y'): 2, ('c', 'e', 'k', 'u'): 2, ('k', 'n', 'u', 'y'): 2, ('e', 'k', 'n', 'u'): 2, ('e', 'k', 'u', 'y'): 2, ('c', 'k', 'n', 't', 'u'): 2, ('c', 'k', 't', 'u', 'y'): 2, ('c', 'e', 'k', 't', 'u'): 2, ('k', 'n', 't', 'u', 'y'): 2, ('e', 'k', 'n', 't', 'u'): 2, ('e', 'k', 't', 'u', 'y'): 2, ('c', 'k', 'n', 'u', 'y'): 2, ('c', 'e', 'k', 'n', 'u'): 2, ('c', 'e', 'k', 'u', 'y'): 2, ('e', 'k', 'n', 'u', 'y'): 2, ('c', 'k', 'n', 't', 'u', 'y'): 2, ('c', 'e', 'k', 'n', 't', 'u'): 2, ('c', 'e', 'k', 't', 'u', 'y'): 2, ('e', 'k', 'n', 't', 'u', 'y'): 2, ('c', 'e', 'k', 'n', 'u', 'y'): 2, ('c', 'e', 'k', 'n', 't', 'u', 'y'): 2, ('i', 'k', 's'): 2, ('i', 'k', 't'): 2, ('i', 'k', 's', 't'): 2, ('e', 'i', 'k'): 2, ('e', 'i', 'k', 't'): 2, ('k', 't', 'y'): 2, ('e', 'k', 't', 'y'): 2, ('c', 'k', 'y'): 2, ('c', 'k', 't', 'y'): 2, ('c', 'e', 'k', 'y'): 2, ('c', 'e', 'k', 't', 'y'): 2, ('k', 'l', 'y'): 2, ('e', 'k', 'l', 'y'): 2, ('e', 'k', 'y'): 3, ('k', 'n', 'y'): 2, ('e', 'k', 'n', 'y'): 2, ('k', 'n', 't'): 2, ('k', 'n', 't', 'y'): 2, ('e', 'k', 'n', 't'): 2, ('e', 'k', 'n', 't', 'y'): 2, ('c', 'k', 'n'): 2, ('c', 'k', 'n', 't'): 2, ('c', 'k', 'n', 'y'): 2, ('c', 'e', 'k', 'n'): 2, ('c', 'k', 'n', 't', 'y'): 2, ('c', 'e', 'k', 'n', 't'): 2, ('c', 'e', 'k', 'n', 'y'): 2, ('c', 'e', 'k', 'n', 't', 'y'): 2, ('a', 'k', 'n'): 2, ('e', 'k', 'n'): 3, ('e', 'k', 'l', 's'): 2, ('e', 'k', 'l', 's', 't'): 2, ('a', 'e', 'k', 's'): 2, ('a', 'e', 'k', 'l', 's'): 4, ('a', 'e', 'k', 's', 't'): 2, ('a', 'e', 'k', 'l', 's', 't'): 2, ('b', 'e', 'k', 's'): 2, ('a', 'b', 'e', 'k', 's'): 4, ('b', 'e', 'k', 'l', 's'): 4, ('b', 'e', 'k', 's', 't'): 2, ('a', 'b', 'e', 'k', 'l', 's'): 4, ('a', 'b', 'e', 'k', 's', 't'): 2, ('b', 'e', 'k', 'l', 's', 't'): 2, ('a', 'b', 'e', 'k', 'l', 's', 't'): 2, ('e', 'k', 's', 't'): 3, ('k', 'o', 's'): 2, ('b', 'k', 'o', 's'): 2, ('k', 'l', 's'): 2, ('a', 'k', 'l', 's'): 4, ('b', 'k', 'l', 's'): 4, ('k', 'l', 's', 't'): 2, ('a', 'b', 'k', 'l', 's'): 4, ('a', 'k', 'l', 's', 't'): 2, ('b', 'k', 'l', 's', 't'): 2, ('a', 'b', 'k', 'l', 's', 't'): 2, ('a', 'k', 's'): 3, ('a', 'b', 'k', 's'): 4, ('a', 'k', 's', 't'): 2, ('a', 'b', 'k', 's', 't'): 2, ('k', 's', 't'): 3, ('b', 'k', 's'): 3, ('b', 'k', 's', 't'): 2, ('b', 'k', 't'): 2, ('b', 'e', 'k', 't'): 2, ('k', 'l', 't'): 2, ('b', 'k', 'l', 't'): 4, ('e', 'k', 'l', 't'): 2, ('b', 'e', 'k', 'l', 't'): 2, ('a', 'k', 't'): 2, ('a', 'k', 'l', 't'): 4, ('a', 'b', 'k', 't'): 4, ('a', 'e', 'k', 't'): 2, ('a', 'b', 'k', 'l', 't'): 4, ('a', 'e', 'k', 'l', 't'): 2, ('a', 'b', 'e', 'k', 't'): 2, ('a', 'b', 'e', 'k', 'l', 't'): 2, ('c', 'k', 't'): 5, ('e', 'k', 't'): 5, ('c', 'e', 'k', 't'): 4, ('e', 'k', 'r'): 2, ('c', 'e', 'k', 'r'): 2, ('a', 'k', 'r'): 2, ('c', 'k', 'r'): 3, ('k', 'o', 'r'): 3, ('b', 'c', 'k'): 2, ('a', 'b', 'c', 'k'): 2, ('b', 'e', 'k'): 2, ('b', 'e', 'k', 'l'): 4, ('a', 'b', 'e', 'k'): 4, ('a', 'b', 'e', 'k', 'l'): 4, ('b', 'k', 'o'): 4, ('b', 'k', 'o', 'o'): 2, ('b', 'k', 'l'): 5, ('a', 'b', 'k', 'l'): 9, ('b', 'k', 'l', 'l'): 2, ('a', 'b', 'k', 'l', 'l'): 2, ('a', 'b', 'k'): 7, ('a', 'a', 'b', 'k'): 2, ('a', 'c', 'k'): 2, ('c', 'e', 'k'): 5, ('k', 'l', 'l'): 2, ('e', 'k', 'l', 'l'): 2, ('a', 'k', 'l', 'l'): 2, ('a', 'e', 'k', 'l', 'l'): 2, ('k', 'l', 'o'): 2, ('a', 'k', 'l', 'o'): 4, ('e', 'k', 'l'): 6, ('a', 'e', 'k', 'l'): 5, ('a', 'k', 'l'): 8, ('a', 'a', 'k', 'l'): 3, ('k', 'o', 'o'): 3, ('a', 'k', 'o', 'o'): 2, ('a', 'k', 'o'): 4, ('a', 'a', 'k', 'o'): 2, ('e', 'k'): 11, ('a', 'e', 'k'): 5, ('a', 'k'): 12, ('a', 'a', 'k'): 2, ('f', 'f'): 2, ('f', 'f', 'o'): 2, ('f', 'g'): 2, ('f', 'g', 'i'): 2, ('f', 'h', 's'): 2, ('f', 'h', 'i', 's'): 3, ('f', 'h', 'i'): 3, ('f', 'u'): 2, ('f', 't', 'u'): 2, ('f', 'n', 'u'): 2, ('e', 'f', 'u'): 2, ('f', 'r', 'u'): 4, ('f', 'i', 'u'): 2, ('f', 'n', 't', 'u'): 2, ('e', 'f', 't', 'u'): 2, ('f', 'r', 't', 'u'): 2, ('f', 'i', 't', 'u'): 2, ('e', 'f', 'n', 'u'): 2, ('f', 'n', 'r', 'u'): 2, ('f', 'i', 'n', 'u'): 2, ('e', 'f', 'r', 'u'): 2, ('e', 'f', 'i', 'u'): 2, ('f', 'i', 'r', 'u'): 2, ('e', 'f', 'n', 't', 'u'): 2, ('f', 'n', 'r', 't', 'u'): 2, ('f', 'i', 'n', 't', 'u'): 2, ('e', 'f', 'r', 't', 'u'): 2, ('e', 'f', 'i', 't', 'u'): 2, ('f', 'i', 'r', 't', 'u'): 2, ('e', 'f', 'n', 'r', 'u'): 2, ('e', 'f', 'i', 'n', 'u'): 2, ('f', 'i', 'n', 'r', 'u'): 2, ('e', 'f', 'i', 'r', 'u'): 2, ('e', 'f', 'n', 'r', 't', 'u'): 2, ('e', 'f', 'i', 'n', 't', 'u'): 2, ('f', 'i', 'n', 'r', 't', 'u'): 2, ('e', 'f', 'i', 'r', 't', 'u'): 2, ('e', 'f', 'i', 'n', 'r', 'u'): 2, ('e', 'f', 'i', 'n', 'r', 't', 'u'): 2, ('a', 'c', 'f'): 2, ('a', 'c', 'f', 'o'): 2, ('a', 'c', 'f', 'i'): 4, ('a', 'c', 'f', 'i', 'o'): 2, ('c', 'e', 'f'): 2, ('c', 'e', 'f', 'o'): 2, ('c', 'e', 'f', 'i'): 2, ('c', 'e', 'f', 'i', 'o'): 2, ('c', 'f', 'o'): 3, ('c', 'f', 'i', 'o'): 4, ('c', 'f', 'i'): 4, ('f', 'r', 's'): 2, ('f', 'i', 's'): 4, ('a', 'f', 'm'): 2, ('a', 'f', 'i', 'm'): 3, ('a', 'f', 'm', 'n'): 2, ('a', 'f', 'm', 'o'): 2, ('a', 'f', 'i', 'm', 'n'): 2, ('a', 'f', 'i', 'm', 'o'): 2, ('a', 'f', 'm', 'n', 'o'): 2, ('a', 'f', 'i', 'm', 'n', 'o'): 2, ('f', 'm', 'n'): 2, ('f', 'i', 'm', 'n'): 4, ('f', 'm', 'n', 'r'): 2, ('f', 'm', 'n', 'o'): 4, ('f', 'i', 'm', 'n', 'r'): 2, ('f', 'i', 'm', 'n', 'o'): 4, ('f', 'm', 'n', 'o', 'r'): 2, ('f', 'i', 'm', 'n', 'o', 'r'): 2, ('f', 'm', 'r'): 3, ('f', 'm', 'o', 'r'): 4, ('f', 'i', 'm'): 3, ('f', 'i', 'm', 'r'): 2, ('f', 'i', 'm', 'o'): 4, ('f', 'i', 'm', 'o', 'r'): 2, ('f', 'm', 'o'): 4, ('a', 'f', 'r', 't'): 2, ('a', 'f', 'i', 'r', 't'): 2, ('a', 'f', 'n', 'r', 't'): 2, ('a', 'f', 'o', 'r', 't'): 2, ('a', 'f', 'i', 'n', 'r', 't'): 2, ('a', 'f', 'i', 'o', 'r', 't'): 2, ('a', 'f', 'n', 'o', 'r', 't'): 2, ('a', 'f', 'i', 'n', 'o', 'r', 't'): 2, ('a', 'f', 'o', 't'): 2, ('a', 'f', 'n', 't'): 2, ('a', 'f', 'n', 'o', 't'): 4, ('a', 'f', 'i', 't'): 2, ('a', 'f', 'i', 'n', 't'): 4, ('a', 'f', 'i', 'o', 't'): 4, ('a', 'f', 'i', 'n', 'o', 't'): 4, ('e', 'f', 't'): 2, ('e', 'f', 'r', 't'): 3, ('f', 'o', 'r', 't'): 3, ('f', 'i', 'o', 'r', 't'): 4, ('f', 'n', 'o', 'r', 't'): 4, ('f', 'i', 'n', 'o', 'r', 't'): 4, ('f', 'n', 'o', 't'): 4, ('f', 'n', 'n', 'o', 't'): 2, ('f', 'i', 'o', 't'): 4, ('f', 'i', 'n', 'o', 't'): 8, ('f', 'i', 'i', 'o', 't'): 2, ('f', 'i', 'i', 'n', 'o', 't'): 2, ('f', 'n', 'r', 't'): 4, ('f', 'i', 'n', 'r', 't'): 6, ('f', 'i', 'n', 't'): 5, ('f', 'i', 'i', 'n', 't'): 2, ('f', 'i', 't'): 4, ('f', 'i', 'r', 't'): 5, ('f', 'r', 't'): 6, ('a', 'd', 'f'): 2, ('a', 'd', 'f', 'r'): 2, ('d', 'f', 'l'): 2, ('a', 'd', 'f', 'l'): 2, ('d', 'f', 'l', 'r'): 2, ('a', 'd', 'f', 'l', 'r'): 2, ('d', 'f', 'i'): 2, ('d', 'e', 'f'): 2, ('d', 'e', 'f', 'l'): 2, ('a', 'd', 'e', 'f'): 2, ('d', 'e', 'f', 'r'): 2, ('a', 'd', 'e', 'f', 'l'): 2, ('d', 'e', 'f', 'l', 'r'): 2, ('a', 'd', 'e', 'f', 'r'): 2, ('a', 'd', 'e', 'f', 'l', 'r'): 2, ('d', 'f', 'r'): 3, ('d', 'f', 'o', 'r'): 2, ('d', 'f', 'o'): 4, ('a', 'f', 'n', 'r'): 4, ('a', 'f', 'n', 'o', 'r'): 6, ('a', 'f', 'i', 'n', 'r'): 8, ('a', 'f', 'i', 'n', 'o', 'r'): 6, ('a', 'f', 'n', 'o'): 6, ('a', 'f', 'i', 'n', 'o'): 12, ('a', 'f', 'n', 'o', 'o'): 2, ('a', 'f', 'i', 'n', 'o', 'o'): 2, ('a', 'f', 'i', 'n'): 8, ('a', 'f', 'i', 'i', 'n'): 4, ('f', 'n', 'r'): 5, ('f', 'i', 'n', 'r'): 8, ('f', 'n', 'o'): 5, ('f', 'n', 'o', 'r'): 5, ('f', 'i', 'n', 'o'): 10, ('f', 'n', 'o', 'o'): 2, ('f', 'i', 'n', 'o', 'r'): 5, ('f', 'n', 'o', 'o', 'r'): 2, ('f', 'i', 'n', 'o', 'o'): 2, ('f', 'i', 'n', 'o', 'o', 'r'): 2, ('f', 'i', 'n'): 10, ('f', 'i', 'i', 'n'): 4, ('e', 'f', 'l', 'r'): 2, ('f', 'i', 'l', 'r'): 3, ('f', 'l', 'o', 'r'): 2, ('f', 'i', 'l', 'o', 'r'): 3, ('f', 'i', 'l', 'o'): 3, ('e', 'f', 'l'): 3, ('f', 'i', 'l'): 5, ('a', 'e', 'f'): 3, ('a', 'e', 'f', 'r'): 3, ('a', 'e', 'f', 'l'): 2, ('a', 'e', 'f', 'l', 'r'): 2, ('a', 'f', 'l', 'r'): 4, ('a', 'f', 'i', 'l', 'r'): 5, ('a', 'f', 'i', 'l'): 6, ('a', 'f', 'i', 'i', 'l'): 2, ('a', 'f', 'l', 'o', 'r'): 3, ('a', 'f', 'i', 'l', 'o', 'r'): 5, ('a', 'f', 'i', 'l', 'o'): 5, ('a', 'f', 'i', 'i', 'l', 'o'): 2, ('a', 'f', 'o', 'r'): 5, ('a', 'f', 'i', 'o', 'r'): 9, ('a', 'f', 'i', 'o'): 9, ('a', 'f', 'i', 'i', 'o'): 4, ('a', 'f', 'r'): 6, ('a', 'f', 'i', 'r'): 7, ('a', 'f', 'i'): 8, ('a', 'f', 'i', 'i'): 3, ('e', 'e', 'f'): 2, ('e', 'e', 'f', 'r'): 2, ('e', 'f', 'o'): 2, ('e', 'f', 'i', 'o'): 2, ('e', 'f', 'i'): 5, ('e', 'f', 'i', 'r'): 3, ('e', 'f', 'r'): 8, ('f', 'i', 'i', 'r'): 2, ('f', 'i', 'i', 'o', 'r'): 3, ('f', 'i', 'o', 'r'): 7, ('f', 'i', 'o', 'o', 'r'): 2, ('f', 'o', 'r'): 9, ('f', 'i'): 17, ('f', 'i', 'i'): 3, ('f', 'o', 'o'): 2, ('f', 'i', 'o', 'o'): 2, ('f', 'i', 'o'): 9, ('f', 'i', 'i', 'o'): 3, ('b', 'w'): 2, ('b', 'e', 'w'): 3, ('b', 'e', 'm'): 2, ('b', 'l', 'm'): 2, ('a', 'b', 'l', 'm'): 4, ('a', 'b', 'm'): 4, ('a', 'a', 'b', 'm'): 6, ('b', 'h'): 3, ('b', 'h', 't'): 2, ('a', 'b', 'h'): 3, ('a', 'b', 'h', 't'): 2, ('b', 'b'): 3, ('a', 'b', 'b'): 5, ('b', 'b', 's'): 2, ('b', 'b', 'e'): 2, ('b', 'b', 'l'): 4, ('a', 'b', 'b', 's'): 2, ('a', 'b', 'b', 'e'): 2, ('a', 'b', 'b', 'l'): 4, ('b', 'b', 'e', 's'): 2, ('b', 'b', 'l', 's'): 2, ('b', 'b', 'e', 'l'): 2, ('a', 'b', 'b', 'e', 's'): 2, ('a', 'b', 'b', 'l', 's'): 2, ('a', 'b', 'b', 'e', 'l'): 2, ('b', 'b', 'e', 'l', 's'): 2, ('a', 'b', 'b', 'e', 'l', 's'): 2, ('a', 'b', 'c'): 3, ('b', 'c', 'u'): 3, ('b', 'c', 'l', 'u'): 3, ('b', 'c', 'l'): 4, ('b', 'n', 'u'): 2, ('b', 'n', 's', 'u'): 3, ('b', 'e', 'n', 'u'): 2, ('b', 'e', 'n', 's', 'u'): 3, ('b', 'e', 'n', 's'): 3, ('b', 'e', 'n', 's', 's'): 3, ('b', 'n', 'r'): 2, ('a', 'b', 'n'): 2, ('b', 'n', 'o'): 3, ('b', 'n', 'o', 's'): 2, ('b', 'n', 's'): 4, ('b', 'n', 's', 's'): 3, ('b', 'd', 'r'): 2, ('a', 'b', 'd', 'r'): 2, ('b', 'o', 'r'): 2, ('b', 'l', 'r'): 2, ('b', 'l', 'r', 'y'): 2, ('b', 'i', 'l', 'r'): 2, ('a', 'b', 'l', 'r'): 2, ('b', 'i', 'l', 'r', 'y'): 2, ('a', 'b', 'l', 'r', 'y'): 2, ('a', 'b', 'i', 'l', 'r'): 2, ('a', 'b', 'i', 'l', 'r', 'y'): 2, ('b', 'i', 'r'): 3, ('a', 'b', 'i', 'r'): 3, ('b', 'r', 'y'): 3, ('b', 'i', 'r', 'y'): 3, ('a', 'b', 'r', 'y'): 3, ('a', 'b', 'i', 'r', 'y'): 3, ('a', 'b', 'r'): 5, ('b', 'd', 'y'): 2, ('a', 'b', 'd'): 4, ('b', 'd', 'o'): 4, ('b', 'e', 'u'): 3, ('b', 'e', 's', 'u'): 3, ('b', 'l', 'u'): 4, ('b', 's', 'u'): 4, ('b', 's', 's', 'u'): 3, ('b', 'i', 'u'): 2, ('b', 'i', 's', 'u'): 3, ('b', 'i', 'y'): 2, ('a', 'b', 'i'): 2, ('a', 'b', 'i', 'y'): 2, ('b', 'i', 's'): 4, ('b', 'i', 's', 's'): 3, ('b', 'e', 'i'): 4, ('b', 'e', 'i', 's'): 5, ('b', 'i', 'l'): 5, ('b', 'i', 't'): 2, ('b', 'e', 'i', 't'): 2, ('b', 'o', 't'): 3, ('b', 'o', 's', 't'): 2, ('b', 'l', 't'): 4, ('b', 'e', 'l', 't'): 4, ('b', 'l', 's', 't'): 4, ('a', 'b', 'l', 't'): 8, ('b', 'l', 'l', 't'): 2, ('b', 'e', 'l', 's', 't'): 4, ('a', 'b', 'e', 'l', 't'): 4, ('b', 'e', 'l', 'l', 't'): 2, ('a', 'b', 'l', 's', 't'): 4, ('b', 'l', 'l', 's', 't'): 2, ('a', 'b', 'l', 'l', 't'): 2, ('a', 'b', 'e', 'l', 's', 't'): 4, ('b', 'e', 'l', 'l', 's', 't'): 2, ('a', 'b', 'e', 'l', 'l', 't'): 2, ('a', 'b', 'l', 'l', 's', 't'): 2, ('a', 'b', 'e', 'l', 'l', 's', 't'): 2, ('b', 's', 't'): 5, ('a', 'b', 's', 't'): 4, ('b', 'e', 't'): 5, ('b', 'e', 's', 't'): 5, ('a', 'b', 'e', 't'): 4, ('a', 'b', 'e', 's', 't'): 4, ('a', 'b', 't'): 7, ('a', 'a', 'b', 't'): 2, ('b', 'o', 'y'): 3, ('a', 'b', 'y'): 5, ('b', 's', 's'): 3, ('b', 'e', 's', 's'): 3, ('b', 'o', 's'): 6, ('b', 'o', 'o', 's'): 2, ('a', 'b', 's'): 8, ('a', 'b', 'l', 's'): 16, ('a', 'b', 'e', 's'): 8, ('a', 'a', 'b', 's'): 4, ('a', 'b', 'e', 'l', 's'): 8, ('a', 'a', 'b', 'l', 's'): 4, ('a', 'a', 'b', 'e', 's'): 4, ('a', 'a', 'b', 'e', 'l', 's'): 4, ('b', 'l', 's'): 9, ('b', 'e', 'l', 's'): 8, ('b', 'l', 'l', 's'): 4, ('b', 'e', 'l', 'l', 's'): 4, ('b', 'e', 's'): 10, ('a', 'b', 'e'): 9, ('a', 'b', 'e', 'l'): 16, ('a', 'a', 'b', 'e'): 4, ('a', 'a', 'b', 'e', 'l'): 4, ('b', 'e', 'l'): 10, ('b', 'e', 'l', 'l'): 4, ('a', 'b', 'o'): 2, ('b', 'l', 'o'): 3, ('b', 'o', 'o'): 4, ('b', 'l', 'l'): 5, ('a', 'b', 'l', 'l'): 8, ('a', 'b', 'l'): 22, ('a', 'a', 'b', 'l'): 14, ('a', 'b'): 27, ('a', 'a', 'b'): 10, ('w', 'y'): 2, ('l', 'w', 'y'): 2, ('g', 'n', 't', 'w'): 2, ('g', 'i', 't', 'w'): 2, ('g', 'i', 'n', 't', 'w'): 2, ('g', 'h', 't', 'w'): 2, ('g', 'h', 'n', 'w'): 2, ('g', 'h', 'n', 't', 'w'): 2, ('g', 'h', 'i', 'n', 'w'): 2, ('g', 'h', 'i', 't', 'w'): 2, ('g', 'h', 'i', 'n', 't', 'w'): 2, ('e', 'g', 'i', 'w'): 2, ('d', 'e', 'g', 'i', 'w'): 2, ('d', 'e', 'g', 'w'): 2, ('d', 'g', 'w'): 2, ('d', 'g', 'n', 'w'): 2, ('d', 'g', 'i', 'w'): 2, ('d', 'g', 'i', 'n', 'w'): 2, ('g', 'i', 'w'): 3, ('g', 'n', 'w'): 3, ('g', 'i', 'n', 'w'): 3, ('p', 's', 'w'): 2, ('p', 'r', 's', 'w'): 2, ('e', 'p', 's', 'w'): 4, ('e', 'p', 'r', 's', 'w'): 2, ('a', 'p', 'w'): 2, ('a', 'p', 's', 'w'): 2, ('a', 'p', 'r', 'w'): 2, ('a', 'e', 'p', 'w'): 4, ('a', 'p', 'r', 's', 'w'): 2, ('a', 'e', 'p', 's', 'w'): 2, ('a', 'e', 'p', 'r', 'w'): 2, ('a', 'e', 'p', 'r', 's', 'w'): 2, ('n', 'p', 'w'): 2, ('a', 'n', 'p', 'w'): 2, ('n', 'p', 's', 'w'): 2, ('n', 'p', 'r', 'w'): 2, ('e', 'n', 'p', 'w'): 4, ('a', 'n', 'p', 's', 'w'): 2, ('a', 'n', 'p', 'r', 'w'): 2, ('a', 'e', 'n', 'p', 'w'): 2, ('n', 'p', 'r', 's', 'w'): 2, ('e', 'n', 'p', 's', 'w'): 2, ('e', 'n', 'p', 'r', 'w'): 2, ('a', 'n', 'p', 'r', 's', 'w'): 2, ('a', 'e', 'n', 'p', 's', 'w'): 2, ('a', 'e', 'n', 'p', 'r', 'w'): 2, ('e', 'n', 'p', 'r', 's', 'w'): 2, ('a', 'e', 'n', 'p', 'r', 's', 'w'): 2, ('p', 'r', 'w'): 3, ('e', 'p', 'r', 'w'): 5, ('e', 'p', 'w'): 5, ('e', 'e', 'p', 'w'): 2, ('w', 'w'): 6, ('w', 'w', 'w'): 2,

{('e', 't'): 108, ('e', 'r'): 114, ('e', 's'): 126, ('e',): 251}

In [102]:
sigma = 100
num_records=len(patterns)
min_support = sigma / num_records
print(f"Minimum support: {min_support}")
# the function find_frequent_patterns takes SIGMA as second parameter
patterns = pyfpgrowth.find_frequent_patterns(associations, sigma)
patterns

Minimum support: 0.019833399444664817

{('high',): 101,
 ('with',): 104,
 ('my',): 110,
 ('home',): 113,
 ('you',): 117,
 ('i',): 117,
 ('is',): 118,
 ('state',): 123,
 ('what',): 128,
 ('city',): 132,
 ('florida',): 136,
 ('school',): 154,
 ('lyrics',): 175,
 ('how',): 178,
 ('how', 'to'): 130,
 ('new',): 222,
 ('http',): 224,
 ('free',): 225,
 ('on',): 232,
 ('county',): 237,
 ('a',): 340,
 ('to',): 426,
 ('and',): 546,
 ('for',): 553,
 ('in', 'the'): 117,
 ('of', 'the'): 207,
 ('in',): 844,
 ('of',): 955}

In [104]:
# number of frequent itemsets found
num_frequent_itemsets = len(patterns)
# maximum size of frequent itemsets
max_itemset_size = max(len(itemset) for itemset in patterns)
print(f'Number of frequent itemsets: {num_frequent_itemsets}')
print(f'Maximum size of frequent itemsets: {max_itemset_size}')

Number of frequent itemsets: 28
Maximum size of frequent itemsets: 2

In [ ]:
support = {key: value / len(df) for key, value in patterns.items()}
support

{('high',): 0.010289323553382234,
 ('with',): 0.010594947025264874,
 ('my',): 0.011206193969030154,
 ('home',): 0.011511817440912795,
 ('you',): 0.011919315403422982,
 ('i',): 0.011919315403422982,
 ('is',): 0.01202118989405053,
 ('state',): 0.012530562347188265,
 ('what',): 0.013039934800325998,
 ('city',): 0.013447432762836185,
 ('florida',): 0.013854930725346373,
 ('school',): 0.015688671556642216,
 ('lyrics',): 0.0178280358598207,
 ('how',): 0.018133659331703342,
 ('how', 'to'): 0.013243683781581092,
 ('new',): 0.022616136919315404,
 ('http',): 0.022819885900570498,
 ('free',): 0.022921760391198046,
 ('on',): 0.023634881825590873,
 ('county',): 0.024144254278728607,
 ('a',): 0.03463732681336593,
 ('to',): 0.04339853300733496,
 ('and',): 0.055623471882640586,
 ('for',): 0.05633659331703342,
 ('in', 'the'): 0.011919315403422982,
 ('of', 'the'): 0.0210880195599022,
 ('in',): 0.08598207008964955,
 ('of',): 0.09729013854930725}

: